### ISSUE TITLE
Change requirements from bullets to todo list

### ISSUE THREAD

**Issue by petr-tik** [cratuki/eng#1]
requirements
Here's what I believe to be the user requirements of an effective OS network API:

- [ ] Open and close a multicast publisher
- [ ] Open and close a multicast subscriber
- [ ] Open and close a UDP-broadcast publisher
- [ ] Open and close a UDP-broadcast subscriber
- [ ] Open and close a UDP unicast publisher
- [ ] Open and close a UDP unicast subscriber
- [ ] Create a TCP client, with clear timeout instruction
- [ ] Create a single-client TCP server
- [ ] Create a multiple-client TCP server
- [ ] Open and close a single-client IPC server that (can be connected to by another process on the same host.)
- [ ] Open and close a IPC connection to an IPC server on the same host, with clear timeout behaviour.
- [ ] Analog to select that tells you about activity across all the open network connections, and which returns enough context to you that it's trivial to know what to do next.

You can go ticking them off, when completed and contributors can immediately see what features they can work on
